### ISSUE TITLE
SER fixture type doesn't line up with the schema

### ISSUE THREAD

**Issue by kaihendry** [Notarise-gov-sg/api-notarise-healthcerts#469]
https://schemata.openattestation.com/sg/gov/moh/pdt-healthcert/2.0/schema.json's `"enum": ["PCR", "ART", "SER"]` doesn't line up with the fixture:

    $ curl -s https://raw.githubusercontent.com/Notarise-gov-sg/api-notarise-healthcerts/master/test/fixtures/v2/pdt_pcr_ser_multi_result_unwrapped.json | grep type | head -n1
      "type": ["PCR", "SER"],

What am I missing? Thanks!

**Comment by HJunyuan** [comment]
The JSON schema describes the possible enum values of: ["PCR", "ART", "SER"]

In the later part of the document, it describes `type` should be either one of the enum or a unique array of the enum:

```json
{
  // ...
  "type": {
      "oneOf": [
        {
          "$ref": "#/definitions/PdtTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PdtTypes"
          },
          "uniqueItems": true,
          "minItems": 1
        }
      ]
    },
 }
```

More info: https://json-schema.org/understanding-json-schema/reference/combining.html#oneof
